[tool.poetry]
name = "deploydocus"
version = "0.1.0"
description = ""
authors = ["Partho Bhowmick <p.s.bhowmick@gmail.com>"]
readme = "README.md"
packages = [{include = "deploydocus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
kubernetes = ">=27 <31"
typer = {extras = ["all"], version = "^0.12"}
pydantic-settings = "^2.2.1"
pyyaml = {extras = ["libyaml"], version = "^6.0"}
types-pyyaml = "^6.0"
pygithub = "^2.3"
plumbum = "^1.8"


[tool.poetry.group.dev.dependencies]
ipython = "^8.21"
pytest = "^8.1"
mypy = "^1.9"
isort = "^5.13"
flake8 = "^7.0"
cython = "^3.0"
wheel = "^0.43"
pypiserver = "^2.0"
camel-converter = "^3.1"
black = "^24.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
