[tool.poetry]
name = "deploydocus"
version = "0.1.0"
description = ""
authors = ["Partho Bhowmick <p.s.bhowmick@gmail.com>"]
readme = "README.md"
packages = [{include = "deploydocus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
kubernetes = "^29.0.0"
typer = "^0.9.0"
pydantic-settings = "^2.1.0"


[tool.poetry.group.dev.dependencies]
ipython = "^8.21.0"
pytest = "^8.0.0"
mypy = "^1.8.0"
black = "^24.1.1"
isort = "^5.13.2"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
